package Gabojago.gabojago_be.exchangeRate;

import java.util.HashMap;
import java.util.Map;

public class CurrencyCountryMapping {
    public static Map<String, String> getMapping() {
        Map<String, String> map = new HashMap<>();
        map.put("KRW", "South Korea");
        map.put("USD", "United States");
        map.put("EUR", "European Union");
        map.put("JPY", "Japan");
        map.put("CNY", "China");
        map.put("GBP", "United Kingdom");
        map.put("AUD", "Australia");
        map.put("CAD", "Canada");
        map.put("AED", "United Arab Emirates");
        map.put("AFN", "Afghanistan");
        map.put("ALL", "Albania");
        map.put("AMD", "Armenia");
        map.put("ANG", "Netherlands Antilles");
        map.put("AOA", "Angola");
        map.put("ARS", "Argentina");
        map.put("AWG", "Aruba");
        map.put("AZN", "Azerbaijan");
        map.put("BAM", "Bosnia and Herzegovina");
        map.put("BBD", "Barbados");
        map.put("BDT", "Bangladesh");
        map.put("BGN", "Bulgaria");
        map.put("BHD", "Bahrain");
        map.put("BIF", "Burundi");
        map.put("BMD", "Bermuda");
        map.put("BND", "Brunei");
        map.put("BOB", "Bolivia");
        map.put("BRL", "Brazil");
        map.put("BSD", "Bahamas");
        map.put("BTN", "Bhutan");
        map.put("BWP", "Botswana");
        map.put("BYN", "Belarus");
        map.put("BZD", "Belize");
        map.put("CDF", "Congo");
        map.put("CHF", "Switzerland");
        map.put("CLP", "Chile");
        map.put("COP", "Colombia");
        map.put("CRC", "Costa Rica");
        map.put("CZK", "Czech Republic");
        map.put("DKK", "Denmark");
        map.put("DOP", "Dominican Republic");
        map.put("DZD", "Algeria");
        map.put("EGP", "Egypt");
        map.put("ETB", "Ethiopia");
        map.put("FJD", "Fiji");
        map.put("GHS", "Ghana");
        map.put("GIP", "Gibraltar");
        map.put("GMD", "Gambia");
        map.put("GNF", "Guinea");
        map.put("GTQ", "Guatemala");
        map.put("HKD", "Hong Kong");
        map.put("HNL", "Honduras");
        map.put("HRK", "Croatia");
        map.put("HUF", "Hungary");
        map.put("IDR", "Indonesia");
        map.put("ILS", "Israel");
        map.put("INR", "India");
        map.put("IQD", "Iraq");
        map.put("IRR", "Iran");
        map.put("ISK", "Iceland");
        map.put("JMD", "Jamaica");
        map.put("JOD", "Jordan");
        map.put("KES", "Kenya");
        map.put("KGS", "Kyrgyzstan");
        map.put("KHR", "Cambodia");
        map.put("KWD", "Kuwait");
        map.put("KZT", "Kazakhstan");
        map.put("LAK", "Laos");
        map.put("LBP", "Lebanon");
        map.put("LKR", "Sri Lanka");
        map.put("LRD", "Liberia");
        map.put("LSL", "Lesotho");
        map.put("LYD", "Libya");
        map.put("MAD", "Morocco");
        map.put("MDL", "Moldova");
        map.put("MGA", "Madagascar");
        map.put("MKD", "North Macedonia");
        map.put("MMK", "Myanmar");
        map.put("MNT", "Mongolia");
        map.put("MOP", "Macau");
        map.put("MUR", "Mauritius");
        map.put("MVR", "Maldives");
        map.put("MWK", "Malawi");
        map.put("MXN", "Mexico");
        map.put("MYR", "Malaysia");
        map.put("MZN", "Mozambique");
        map.put("NAD", "Namibia");
        map.put("NGN", "Nigeria");
        map.put("NOK", "Norway");
        map.put("NPR", "Nepal");
        map.put("NZD", "New Zealand");
        map.put("OMR", "Oman");
        map.put("PEN", "Peru");
        map.put("PGK", "Papua New Guinea");
        map.put("PHP", "Philippines");
        map.put("PKR", "Pakistan");
        map.put("PLN", "Poland");
        map.put("PYG", "Paraguay");
        map.put("QAR", "Qatar");
        map.put("RON", "Romania");
        map.put("RSD", "Serbia");
        map.put("RUB", "Russia");
        map.put("RWF", "Rwanda");
        map.put("SAR", "Saudi Arabia");
        map.put("SCR", "Seychelles");
        map.put("SEK", "Sweden");
        map.put("SGD", "Singapore");
        map.put("SLL", "Sierra Leone");
        map.put("SOS", "Somalia");
        map.put("SRD", "Suriname");
        map.put("SZL", "Swaziland");
        map.put("THB", "Thailand");
        map.put("TJS", "Tajikistan");
        map.put("TMT", "Turkmenistan");
        map.put("TND", "Tunisia");
        map.put("TRY", "Turkey");
        map.put("TTD", "Trinidad and Tobago");
        map.put("TWD", "Taiwan");
        map.put("TZS", "Tanzania");
        map.put("UAH", "Ukraine");
        map.put("UGX", "Uganda");
        map.put("UYU", "Uruguay");
        map.put("UZS", "Uzbekistan");
        map.put("VES", "Venezuela");
        map.put("VND", "Vietnam");
        map.put("XAF", "Central Africa");
        map.put("XCD", "Eastern Caribbean");
        map.put("XOF", "West Africa");
        map.put("YER", "Yemen");
        map.put("ZAR", "South Africa");
        map.put("ZMW", "Zambia");
        map.put("ZWL", "Zimbabwe");

        return map;
    }
}
