services:
  app:
    container_name: gabojago_be-app
    hostname: gabojago_be-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_HOST: ${SSH_HOST}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    networks:
      - gabojago_network
    env_file:
      - docker-elements.env

networks:
  gabojago_network:
    name: gabojago_network
    driver: bridge
